import Link from 'next/link';

const circuits = [
  {
    id: 'Circuit 1',
    name: 'KYC Proof',
    file: 'circuits/kyc/src/main.nr',
    color: 'border-violet-500 text-violet-400',
    bg: 'bg-violet-500/5',
    inputs: ['kyc_hash', 'secret', 'credential_commitment', 'note_commitment', 'nullifier', 'amount'],
    outputs: ['Valid commitment proof'],
    desc: 'Proves that credential_commitment = Poseidon2(kyc_hash, secret) without revealing either input. Generated by the depositor.',
  },
  {
    id: 'Circuit 2',
    name: 'Withdrawal Proof',
    file: 'circuits/withdrawal/src/main.nr',
    color: 'border-cyan-500 text-cyan-400',
    bg: 'bg-cyan-500/5',
    inputs: ['note_commitment', 'secret', 'nullifier', 'recipient', 'amount'],
    outputs: ['Valid spend proof'],
    desc: 'Proves knowledge of secret behind note_commitment and produces a unique nullifier. Prevents double-spending.',
  },
  {
    id: 'Circuit 3',
    name: 'ASP Sanctions Proof',
    file: 'circuits/asp/src/main.nr',
    color: 'border-orange-500 text-orange-400',
    bg: 'bg-orange-500/5',
    inputs: ['address', 'merkle_root', 'merkle_path', 'merkle_indices'],
    outputs: ['Non-inclusion proof'],
    desc: 'Proves address is NOT in the OFAC sanctions Merkle tree. Required for all withdrawals to enforce compliance.',
  },
];

const layers = [
  {
    label: 'Noir Circuits',
    color: 'bg-violet-500/20 border-violet-500/40 text-violet-300',
    items: ['kyc.nr', 'withdrawal.nr', 'asp.nr'],
    desc: 'UltraPlonk ZK proofs',
  },
  {
    label: 'Soroban Contract',
    color: 'bg-cyan-500/20 border-cyan-500/40 text-cyan-300',
    items: ['deposit()', 'withdraw()', 'nullifier_set', 'commitment_map'],
    desc: 'BN254 g1_is_on_curve · g1_msm · pairing_check (CAP-0074) + poseidon2_permutation (CAP-0075)',
  },
  {
    label: 'Stellar Anchor',
    color: 'bg-emerald-500/20 border-emerald-500/40 text-emerald-300',
    items: ['SEP-10 auth', 'SEP-12 KYC PUT', 'SEP-06/31/38 tx'],
    desc: 'Identity & compliance layer',
  },
  {
    label: 'CLI',
    color: 'bg-orange-500/20 border-orange-500/40 text-orange-300',
    items: ['deposit.ts', 'withdraw.ts', 'audit.ts'],
    desc: 'TypeScript client tooling',
  },
];

const sep = [
  { id: 'SEP-10', name: 'Stellar Web Auth', desc: 'Challenge-response auth with Stellar keypair. Used to gate all anchor interactions.' },
  { id: 'SEP-12', name: 'KYC API', desc: 'Anchor receives credential_commitment field. Associates ZK commitment with verified account.' },
  { id: 'SEP-06', name: 'Simple Transfer', desc: 'Deposit/withdrawal flow for basic cross-border transfers with shielded amounts.' },
  { id: 'SEP-31', name: 'Cross-Border', desc: 'B2B payment rails wrapped with privacy layer. Sender/receiver identities off-chain.' },
  { id: 'SEP-38', name: 'Anchor RFQ', desc: 'Quote and exchange flow — rate negotiation happens before ZK proof generation.' },
];

export default function ArchitecturePage() {
  return (
    <div className="max-w-5xl mx-auto space-y-12">
      {/* Header */}
      <div>
        <h1 className="text-4xl font-black text-veil-text">Architecture</h1>
        <p className="text-veil-muted mt-2 text-sm leading-relaxed max-w-2xl">
          StellarVeil is a privacy protocol built on three Noir ZK circuits, a Soroban smart contract,
          and the Stellar anchor SEP standards for compliant identity verification.
        </p>
      </div>

      {/* System overview diagram */}
      <section className="space-y-4">
        <h2 className="text-xl font-bold text-veil-text">System Overview</h2>
        <div className="bg-veil-card border border-veil-border rounded-2xl p-6 overflow-x-auto">
          <div className="min-w-[600px]">
            {/* User row */}
            <div className="flex justify-center mb-6">
              <div className="bg-veil-bg border-2 border-veil-primary rounded-xl px-6 py-3 text-center">
                <div className="text-2xl mb-1">👤</div>
                <div className="text-sm font-bold text-veil-text">User / CLI</div>
                <div className="text-xs text-veil-muted">Stellar keypair + secret</div>
              </div>
            </div>

            {/* Arrows down to 3 columns */}
            <div className="flex justify-center mb-2">
              <div className="text-veil-border text-2xl">↙ ↓ ↘</div>
            </div>

            {/* Three columns */}
            <div className="grid grid-cols-3 gap-4 mb-4">
              {[
                { icon: '⚓', label: 'Stellar Anchor', sub: 'SEP-10/12', border: 'border-emerald-500/40', bg: 'bg-emerald-500/5', text: 'text-emerald-400' },
                { icon: '⚡', label: 'Noir Prover', sub: 'UltraPlonk', border: 'border-violet-500/40', bg: 'bg-violet-500/5', text: 'text-violet-400' },
                { icon: '🛡', label: 'ASP Server', sub: 'Merkle tree', border: 'border-orange-500/40', bg: 'bg-orange-500/5', text: 'text-orange-400' },
              ].map((c) => (
                <div key={c.label} className={`border ${c.border} ${c.bg} rounded-xl p-4 text-center`}>
                  <div className="text-2xl mb-1">{c.icon}</div>
                  <div className={`text-sm font-bold ${c.text}`}>{c.label}</div>
                  <div className="text-xs text-veil-muted">{c.sub}</div>
                </div>
              ))}
            </div>

            {/* Down arrow to Soroban */}
            <div className="flex justify-center mb-2">
              <div className="text-veil-border text-2xl">↘ ↓ ↙</div>
            </div>

            {/* Soroban */}
            <div className="flex justify-center">
              <div className="bg-veil-bg border-2 border-cyan-500/50 rounded-xl px-8 py-4 text-center max-w-xs">
                <div className="text-2xl mb-1">📦</div>
                <div className="text-sm font-bold text-cyan-400">Soroban Contract</div>
                <div className="text-xs text-veil-muted">g1_is_on_curve · g1_msm · pairing_check · poseidon2_permutation</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Stack layers */}
      <section className="space-y-4">
        <h2 className="text-xl font-bold text-veil-text">Protocol Layers</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
          {layers.map((l) => (
            <div key={l.label} className={`border ${l.color} rounded-2xl p-5 space-y-3`}>
              <div className={`text-xs font-black uppercase tracking-widest ${l.color.split(' ')[2]}`}>{l.label}</div>
              <div className="text-xs text-veil-muted">{l.desc}</div>
              <ul className="space-y-1">
                {l.items.map((item) => (
                  <li key={item} className="text-xs font-mono text-veil-text bg-black/20 rounded px-2 py-0.5">
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* Circuits detail */}
      <section className="space-y-4">
        <h2 className="text-xl font-bold text-veil-text">Noir Circuits</h2>
        <div className="space-y-4">
          {circuits.map((c) => (
            <div key={c.id} className={`bg-veil-card border ${c.color.split(' ')[0]} rounded-2xl p-6 space-y-4`}>
              <div className="flex items-start justify-between gap-4 flex-wrap">
                <div>
                  <div className={`text-xs font-mono font-black ${c.color.split(' ')[1]}`}>{c.id}</div>
                  <h3 className="text-lg font-bold text-veil-text mt-0.5">{c.name}</h3>
                  <p className="text-sm text-veil-muted mt-1">{c.desc}</p>
                </div>
                <div className="text-xs font-mono text-veil-muted bg-veil-bg border border-veil-border rounded-lg px-3 py-1.5 shrink-0">
                  {c.file}
                </div>
              </div>
              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <div className="text-xs text-veil-muted mb-2 font-semibold uppercase tracking-wide">Inputs (private witnesses)</div>
                  <div className="flex flex-wrap gap-1.5">
                    {c.inputs.map((inp) => (
                      <span key={inp} className={`text-xs font-mono px-2 py-0.5 rounded-full border ${c.color} ${c.bg}`}>
                        {inp}
                      </span>
                    ))}
                  </div>
                </div>
                <div>
                  <div className="text-xs text-veil-muted mb-2 font-semibold uppercase tracking-wide">Output</div>
                  <div className="flex flex-wrap gap-1.5">
                    {c.outputs.map((out) => (
                      <span key={out} className="text-xs font-mono px-2 py-0.5 rounded-full border border-veil-success/30 text-veil-success bg-veil-success/5">
                        {out}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* SEP standards */}
      <section className="space-y-4">
        <h2 className="text-xl font-bold text-veil-text">Stellar Ecosystem Standards (SEPs)</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {sep.map((s) => (
            <div key={s.id} className="bg-veil-card border border-veil-border rounded-xl p-4 space-y-2">
              <div className="text-xs font-mono font-black text-veil-primary">{s.id}</div>
              <div className="font-semibold text-veil-text text-sm">{s.name}</div>
              <div className="text-xs text-veil-muted leading-relaxed">{s.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Test coverage */}
      <section className="bg-veil-card border border-veil-border rounded-2xl p-6 space-y-4">
        <h2 className="text-xl font-bold text-veil-text">Test Coverage</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { file: 'kyc.test.ts', count: 16, color: 'text-violet-400' },
            { file: 'withdrawal.test.ts', count: 16, color: 'text-cyan-400' },
            { file: 'asp.test.ts', count: 8, color: 'text-orange-400' },
            { file: 'stellarveil.test.ts', count: 12, color: 'text-emerald-400' },
            { file: 'deposit.test.ts', count: 8, color: 'text-pink-400' },
            { file: 'withdraw.test.ts', count: 6, color: 'text-yellow-400' },
            { file: 'audit.test.ts', count: 4, color: 'text-blue-400' },
            { file: 'adversarial.test.ts', count: 3, color: 'text-red-400' },
          ].map((t) => (
            <div key={t.file} className="bg-veil-bg border border-veil-border rounded-xl p-3">
              <div className={`text-xl font-black ${t.color}`}>{t.count}</div>
              <div className="text-xs font-mono text-veil-muted mt-0.5">{t.file}</div>
            </div>
          ))}
        </div>
        <div className="text-center pt-2">
          <span className="text-2xl font-black text-veil-success">73</span>
          <span className="text-veil-muted text-sm ml-2">tests passing · 0 failing</span>
        </div>
      </section>

      {/* Links */}
      <div className="flex gap-3 flex-wrap">
        <a
          href="https://github.com/sodiq-code/stellarveil"
          target="_blank"
          rel="noopener noreferrer"
          className="px-5 py-2.5 bg-veil-card border border-veil-border hover:border-veil-primary text-veil-muted hover:text-veil-text rounded-xl text-sm transition-colors"
        >
          View Source on GitHub ↗
        </a>
        <Link
          href="/send"
          className="px-5 py-2.5 bg-veil-primary hover:bg-violet-500 text-white rounded-xl text-sm font-semibold transition-colors glow-violet"
        >
          Try the Protocol →
        </Link>
      </div>
    </div>
  );
}
